spring:
  application:
    name: wecall-backend
server:
  port: ${SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
